type = "DoodadMaterial"


[material.base]  
base_color_texture="/textures/material_overrides/pixel/overgrown_pixel_dungeon.png"
normal_map_texture="/textures/material_overrides/pixel/overgrown_pixel_dungeon_normal.png"
perceptual_roughness= 0.9
base_color={ LinearRgba = [0.8,0.8,0.8, 1.0] }
double_sided= true
alpha_mode=   { Mask = 0.2 }

[properties]
uv_scale_factor= 1.0 



[properties.texture_subset_dimensions]
offset= [ 0,32 ]
dimensions= [32,32]
base_texture_dimensions= [352,272]
 
