type = "MagicFxMaterial"

[material.base]  
base_color = { LinearRgba = [0.588, 0.255, 0.239, 1.0 ] }
emissive= [0.588,0.255,0.239,2.0]   
double_sided= true
alpha_mode=  "Blend"                       



[material.extension]
base_color_texture = "/textures/vfx_textures/kenney/fire_01.png"
masking_texture= "/textures/pixel_particles.png"




[material.extension.custom_uniforms]
scroll_repeats = [ 2.0,2.0]
scroll_speed = [0.25,0.12]
distortion_amount = 0.02
distortion_speed = [0.02,0.01]
uv_input_scale= [4.0,4.0] 
use_masking_texture=1
animate_masking_texture=0